# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Blog Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn compile
      
  test:
    runs-on: ubuntu-latest
    name: Running tests with coverage
    needs: compile
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: cubestackblog
          POSTGRES_PASSWORD: cubestackblog
          POSTGRES_DB: cubestackblog
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn test
      - name: Code coverage
        run: mvn jacoco:report

  build:
    runs-on: ubuntu-latest
    name: Run mvn build
    needs: test
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: cubestackblog
          POSTGRES_PASSWORD: cubestackblog
          POSTGRES_DB: cubestackblog
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
